[tools]
node = "24"
pnpm = "10"

[tasks.setup]
description = "Setup the project environment"
run = "pnpm install"

[tasks.dev]
description = "Start the development server"
depends = ["setup"]
run = "pnpm dev"
